name: tf-setup

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:    
    HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
    HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
    TF_LOG: DEBUG
    TF_LOG_PATH: ${{ github.workspace }}/terraform.log
            
jobs:
    Terraform-plan-apply:
        runs-on: ubuntu-latest
        steps:
            - name: install-tfenv
              run: git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv

            - name: make-tfenv-folder
              run: mkdir -p ~/.local/bin/                           

            - name: soft-linking
              run: ln -s ~/.tfenv/bin/* ~/.local/bin    
            
            - name: install-terraform
              run: tfenv install 1.10.3

            - name: set-terraform-version
              run: tfenv use 1.10.3

            - name: checkout-tf-plans
              uses: actions/checkout@v2            
            
            - name: tf-init
              run: terraform init --backend-config="access_key=${{secrets.HW_ACCESS_KEY}}"  --backend-config="secret_key=${{secrets.HW_SECRET_KEY}}"

            - name: tf-plan
              run: terraform plan 

            - name: tf-apply
              run: terraform apply -auto-approve

            - uses: actions/upload-artifact@v4
              if: always()
              with:
                name: error.log
                path: ${{ github.workspace }}/terraform.log
    
